"""create channel_configs table

Revision ID: 5c7b62e589f9
Revises: b0a31c003a59
Create Date: 2025-12-02 10:46:53.129589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7b62e589f9'
down_revision: Union[str, Sequence[str], None] = 'b0a31c003a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(length=50), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('api_secret', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_configs_channel_name'), 'channel_configs', ['channel_name'], unique=True)
    op.create_index(op.f('ix_channel_configs_id'), 'channel_configs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_configs_id'), table_name='channel_configs')
    op.drop_index(op.f('ix_channel_configs_channel_name'), table_name='channel_configs')
    op.drop_table('channel_configs')
    # ### end Alembic commands ###
